apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: astroturf
  namespace: default
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: astroturf
    spec:
      containers:
      - image: gcr.io/beimo-879dc/astroturf:e4de5a7980a7161dc78368df2984fab3ce43c375
        imagePullPolicy: IfNotPresent
        name: astroturf
        ports:
        - containerPort: 3000
