apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: astroturf
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: astroturf
    spec:
      containers:
        - name: astroturf
          image: gcr.io/beimo-879dc/astroturf:fbc37c68b27691c32dac56a44c3c4de368204e46
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
