apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: astroturf
  namespace: default
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: astroturf
    spec:
      containers:
      - imagePullPolicy: IfNotPresent
        name: astroturf
        ports:
        - containerPort: 3000
