apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: astroturf
  namespace: default
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: astroturf
    spec:
      containers:
      - image: gcr.io/beimo-879dc/astroturf:32678e15b287d1db7912ea1a6b14f997cc427527
        imagePullPolicy: IfNotPresent
        name: astroturf
        ports:
        - containerPort: 3000
