apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: astroturf
  namespace: default
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: astroturf
    spec:
      containers:
      - image: gcr.io/beimo-879dc/astroturf:6c8ab29b5dbe603f7c1fda847bcc1b9db411a2b9
        imagePullPolicy: IfNotPresent
        name: astroturf
        ports:
        - containerPort: 3000
